server:
  port: 5001
app:
  doc:
    appName: ApplyFlowAuth
    version: 1.0.0
spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.2ewpa.mongodb.net/login?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.service.roundrobin@gmail.com
    password: mygjrsugaitzqsrr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:configserver:http://host.docker.internal:4998
  main:
    allow-bean-definition-overriding: true

