server:
  port: 5001
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0.2ewpa.mongodb.net/login?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: no.reply.service.roundrobin@gmail.com
    password: mygjrsugaitzqsrr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: optional:configserver:http://localhost:4998
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://securetoken.google.com/apply-f520b




