server:
  port: 5000
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:4998
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**,/auth/**
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/flow/**
