server:
  port: 5000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**, /auth-service/**
  config:
    import: optional:configserver:http://localhost:4998
